### ISSUE TITLE
Change auth:rule parsing

### ISSUE THREAD

**Issue by AirCrisp** [toa-io/toa#545]
Following syntax is ok:
```
        auth:rule:
          id: moderator
          role: app:once:moderator
```

But this is not working:
```
        auth:rule:
          auth:id: moderator
          auth:role: app:once:moderator
```
Error:
```
AssertionError ¡ERR_ASSERTION¿: Directive 'auth:id' is not provided by the 'auth' family.
    at Authorization.create (/home/aircrisp/sdgroup/depic.toa/node_modules/§toa.io/extensions.exposition/source/directives/auth/Authorization.ts:40:12)
    at new Rule (/home/aircrisp/sdgroup/depic.toa/node_modules/§toa.io/extensions.exposition/source/directives/auth/Rule.ts:9:25)
    at /home/aircrisp/sdgroup/depic.toa/node_modules/§toa.io/extensions.exposition/source/directives/auth/Authorization.ts:50:19
    at apply (/home/aircrisp/sdgroup/depic.toa/node_modules/matchacho/source/apply.ts:4:14)
    at match (/home/aircrisp/sdgroup/depic.toa/node_modules/matchacho/source/match.ts:29:19)
    at Authorization.create (/home/aircrisp/sdgroup/depic.toa/node_modules/§toa.io/extensions.exposition/source/directives/auth/Authorization.ts:48:17)
    at DirectivesFactory.create (/home/aircrisp/sdgroup/depic.toa/node_modules/§toa.io/extensions.exposition/source/Directive.ts:66:32)
    at createMethod (/home/aircrisp/sdgroup/depic.toa/node_modules/§toa.io/extensions.exposition/source/RTD/factory.ts:37:49)
    at createNode (/home/aircrisp/sdgroup/depic.toa/node_modules/§toa.io/extensions.exposition/source/RTD/factory.ts:18:28)
    at createRoute (/home/aircrisp/sdgroup/depic.toa/node_modules/§toa.io/extensions.exposition/source/RTD/factory.ts:28:16) °
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
```

Expected result: both variants have to work

**Comment by temich** [comment]
https://github.com/toa-io/toa/commit/0f5dc7c4580323107df153a5ed31967a9f72a92c
